// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgdrbimchwxbfyourqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnZHJiaW1jaHd4YmZ5b3VycWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NDY4MDYsImV4cCI6MjA2NDIyMjgwNn0.5SmdFhO9ePkEQsPTv_RqaRpGLXuv55kK8OlNETAZ23k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);